# Generated by Django 3.0.4 on 2023-05-13 02:55

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lishi_ShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=124, verbose_name='date')),
                ('Total_radiation', models.FloatField(default=0.0, max_length=124, verbose_name='Total_radiation')),
                ('Direct_radiation', models.FloatField(default=0.0, verbose_name='Direct_radiation')),
                ('Diffuse_radiation', models.FloatField(default=0.0, verbose_name='Diffuse_radiation')),
                ('Temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
                ('Pressure', models.FloatField(default=0.0, verbose_name='Pressure')),
                ('Humidity', models.FloatField(default=0.0, verbose_name='Humidity')),
                ('Actual_power', models.FloatField(default=0.0, verbose_name='Actual_power')),
                ('Rated_power', models.FloatField(default=0.0, verbose_name='Rated_power')),
            ],
            options={
                'verbose_name': 'Historical Information Sheet',
                'verbose_name_plural': 'Historical Information Sheet',
            },
        ),
        migrations.CreateModel(
            name='Lishi_YuCe_ShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=124, verbose_name='date')),
                ('Total_radiation', models.FloatField(default=0.0, max_length=124, verbose_name='Total_radiation')),
                ('Direct_radiation', models.FloatField(default=0.0, verbose_name='Direct_radiation')),
                ('Diffuse_radiation', models.FloatField(default=0.0, verbose_name='Diffuse_radiation')),
                ('Temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
                ('Pressure', models.FloatField(default=0.0, verbose_name='Pressure')),
                ('Humidity', models.FloatField(default=0.0, verbose_name='Humidity')),
                ('Actual_power', models.FloatField(default=0.0, verbose_name='Actual_power')),
                ('Rated_power', models.FloatField(default=0.0, verbose_name='Rated_power')),
            ],
            options={
                'verbose_name': 'Historical Forecast Information Sheet',
                'verbose_name_plural': 'Historical Forecast Information Sheet',
            },
        ),
        migrations.CreateModel(
            name='ShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=124, verbose_name='date')),
                ('Total_radiation', models.FloatField(default=0.0, max_length=124, verbose_name='Total_radiation')),
                ('Direct_radiation', models.FloatField(default=0.0, verbose_name='Direct_radiation')),
                ('Diffuse_radiation', models.FloatField(default=0.0, verbose_name='Diffuse_radiation')),
                ('Temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
                ('Pressure', models.FloatField(default=0.0, verbose_name='Pressure')),
                ('Humidity', models.FloatField(default=0.0, verbose_name='Humidity')),
                ('Actual_power', models.FloatField(default=0.0, verbose_name='Actual_power')),
                ('Rated_power', models.FloatField(default=0.0, verbose_name='Rated_power')),
                ('type', models.CharField(default='', max_length=16, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Information Form',
                'verbose_name_plural': 'Information Form',
            },
        ),
        migrations.CreateModel(
            name='YuCe_ShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=124, verbose_name='date')),
                ('Total_radiation', models.FloatField(default=0.0, max_length=124, verbose_name='Total_radiation')),
                ('Direct_radiation', models.FloatField(default=0.0, verbose_name='Direct_radiation')),
                ('Diffuse_radiation', models.FloatField(default=0.0, verbose_name='Diffuse_radiation')),
                ('Temperature', models.FloatField(default=0.0, verbose_name='Temperature')),
                ('Pressure', models.FloatField(default=0.0, verbose_name='Pressure')),
                ('Humidity', models.FloatField(default=0.0, verbose_name='Humidity')),
                ('Actual_power', models.FloatField(default=0.0, verbose_name='Actual_power')),
                ('Rated_power', models.FloatField(default=0.0, verbose_name='Rated_power')),
                ('type', models.CharField(default='', max_length=16, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Forecast Information Form',
                'verbose_name_plural': 'Forecast Information Form',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.CharField(default='18', max_length=16, verbose_name='age')),
                ('set', models.CharField(choices=[('man', 'man'), ('woman', 'woman')], default='man', max_length=12, verbose_name='sex')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Table',
                'verbose_name_plural': 'User Table',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
