"""
Django settings for KeShiHua project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(fksie^4=h9dj6u#nq326p&qz$bsv@5@e78n2p2kt8d$#drxd)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

INSTALLED_APPS = [
    'KeShiHua.apps.KeShiHuaConfig',
    'simpleui',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monitor.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

AUTH_USER_MODEL = "KeShiHua.Users"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
SIMPLEUI_INDEX = 'http://127.0.0.1:8000/admin'
SIMPLEUI_HOME_INFO = False
SIMPLEUI_STATIC_OFFLINE = True
SIMPLEUI_DEFAULT_THEME = 'element.css'
SIMPLEUI_LOGO = 'https://cdn1.iconfinder.com/data/icons/real-estate-building-flat-vol-1/104/building__house__home__real__estate-512.png'

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': False,
    'menus': [{
        'name': 'Real-time Monitoring',
        'icon': 'fa fa-book-open',
        'models': [
            {
                'name': 'Area 1 Real-time Monitoring',
                'url': '/jiankong?types=1',
                'icon': 'far fa-surprise'
            },
            {
                'name': 'Area 2 Real-time Monitoring',
                'url': '/jiankong?types=2',
                'icon': 'far fa-surprise'
            },
            {
                'name': 'Area 3 Real-time Monitoring',
                'url': '/jiankong?types=3',
                'icon': 'far fa-surprise'
            },
        ]
    },
        {
            'name': 'Forecast Analysis',
            'icon': 'fa fa-book-open',
            'models': [
                {
                    'name': 'Area 1 Forecast Analysis',
                    'url': '/yuce?types=1',
                    'icon': 'far fa-surprise'
                },
                {
                    'name': 'Area 2 Forecast Analysis',
                    'url': '/yuce?types=2',
                    'icon': 'far fa-surprise'
                },
                {
                    'name': 'Area 3 Forecast Analysis',
                    'url': '/yuce?types=3',
                    'icon': 'far fa-surprise'
                },
            ]
        },
        {
            'name': 'Warning Control',
            'icon': 'fa fa-book-open',
            'models': [
                {
                    'name': 'Warning',
                    'url': '/yujing',
                    'icon': 'far fa-surprise'
                }

            ]
        },
        {
            'name': 'Information Viewing Homepage',
            'url': '/chakan',
            'icon': 'far fa-surprise'
        },

    ]
}

